---
- name: install nginx
  yum: name=nginx state=installed

- name: start nginx
  service: name=nginx state=started enabled=true

- name: templating /etc/nginx/nginx.conf
  template:
   src: nginx.conf.j2
   dest: /etc/nginx/nginx.conf
   owner: "{{ nginx_user }}"
   group: "{{ nginx_group }}"
   mode: '0644'
   backup: yes

- name: replacing /usr/share/nginx/html
  template:
   src: index.html.j2
   dest: /usr/share/nginx/html/index.html
   owner: "{{ nginx_user }}"
   group: "{{ nginx_group }}"
   mode: '0744'
   backup: yes

- name: restart nginx
  service: name=nginx state=restarted
