---
- name: backends
  hosts: backends
  become: yes
  become_user: root
  remote_user: vagrant
  tasks:

    - name: install nginx
      yum: name=nginx state=installed

    - name: start nginx
      service: name=nginx state=started enabled=true

    - name: replacing /etc/nginx/nginx.conf
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: replacing /usr/share/nginx/html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0744'
        backup: yes

    - name: restart nginx
      service: name=nginx state=restarted
