---
- name: loops users
  hosts: centos1.example.com
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
  vars_files:
   - mygroups.yml
  tasks:
   - name: create users
     user: name="user{{ item }}" state=present
     with_sequence: start=1 end=50
   - name: create groups
     group: name="{{ item.key }}" gid="{{ item.value.gid }}"
     with_dict: "{{ mygroups }}"
   - name: create myusers0
     user: name="{{ item.value.members[0] }}" state=present groups="{{ item.value.gid }}"
     with_dict: "{{ mygroups }}"
   - name: create myusers1
     user: name="{{ item.value.members[1] }}" state=present groups="{{ item.value.gid }}"
     with_dict: "{{ mygroups }}"
   - name: create myusers2
     user: name="{{ item.value.members[2] }}" state=present groups="{{ item.value.gid }}"
     with_dict: "{{ mygroups }}"

