$script = <<SCRIPT
	useradd -m mgmt
	echo Ansible123|passwd --stdin mgmt
	echo "mgmt ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/mgmt
	sed -i.bak -e "s/asswordAuthentication no/asswordAuthentication yes/" /etc/ssh/sshd_config
	mkdir /home/mgmt/.ssh
	chown mgmt:mgmt /home/mgmt/.ssh
	chmod 0700 /home/mgmt/.ssh
	systemctl restart sshd
SCRIPT

Vagrant.configure(2) do |config|

	config.vm.define "centos1" do |conf|
		conf.vm.box = "centos/7"
		conf.vm.hostname = 'centos1.example.com'
		conf.vm.network "private_network", ip: "172.28.128.16"
                conf.vm.provision "shell", inline: $script
	end

	config.vm.define "centos2" do |conf|
		conf.vm.box = "centos/7"
		conf.vm.hostname = 'centos2.example.com'
		conf.vm.network "private_network", ip: "172.28.128.17"
                conf.vm.provision "shell", inline: $script
	end

	config.vm.define "ansible" do |conf|
                conf.vm.box = "centos/7"
                conf.vm.hostname = 'ansible.example.com'
                conf.vm.network "private_network", ip: "172.28.128.15"
		conf.vm.provision "shell", inline: $script
                conf.vm.provision "shell", inline: <<-SHELL
                        yum install epel-release -y
                        yum install ansible -y
			useradd -m devops
			echo Ansible123|passwd --stdin devops
			echo "devops ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/devops
			mkdir /home/devops/.ssh
			chown devops:devops /home/devops/.ssh
			chmod 0700 /home/devops/.ssh
			mkdir -p /home/devops/ansible/inventory
                        cp /vagrant/ansible.cfg /home/devops/ansible/ansible.cfg
                        echo  "export ANSIBLE_CONFIG=/home/devops/ansible/ansible.cfg" >> /etc/bashrc
			cp /vagrant/invfile /home/devops/ansible/inventory/
			export ANSIBLE_CONFIG=/home/devops/ansible/ansible.cfg
			su devops -c "ssh-keygen -f /home/devops/.ssh/id_rsa -t rsa -N ''"
			ansible all -m copy -a "src=/home/devops/.ssh/id_rsa.pub dest=/home/mgmt/.ssh/authorized_keys mode=0600"
                SHELL
        end

end
