---

- name: start httpd playbook
  hosts: examservers
  become: yes
  become_user: root
  remote_user: vagrant
  tasks: 
   - name: start httpd
     service:
      name: httpd
      state: started
      enabled: true
